### ISSUE TITLE
pydolphinscheduler is having problems using the official documentation code

### ISSUE THREAD

**Issue by Treasure-u** [apache/dolphinscheduler-sdk-python#98]
The version of my pydolphinscheduler is 4.0.3, and dolphinscheduler is 3.1.5. , my OS is ubuntu 22.10，Other than that,I use hdfs for the resource center. 
When I run code in the official documentation
<img width="750" alt="image" src="https://github.com/apache/dolphinscheduler-sdk-python/assets/82716144/17523912-b46f-4f8c-a5aa-fa6f5becc1e5">
something wrong happened.I was able to upload main.py and dependence.py without a problem, but my workflow didn't work. When I look at the log it says the host instance does not exist.
<img width="1582" alt="截屏2023-08-01 09 48 39" src="https://github.com/apache/dolphinscheduler-sdk-python/assets/82716144/27ec493f-ae34-4477-a9ac-c50d83ed140f">
<img width="1571" alt="image" src="https://github.com/apache/dolphinscheduler-sdk-python/assets/82716144/f8e8d679-820e-4105-89f0-ae425aa5d71f">
<img width="859" alt="image" src="https://github.com/apache/dolphinscheduler-sdk-python/assets/82716144/4bd030fd-5af2-4c40-9c61-89035fa2100c">

**Comment by zhongjiajie** [comment]
Hi @Treasure-u , do you mean both resource files and workflow created success, but when you run the workflow and go to see the workflow/task instance log is show's host is empty?


If in this situation, could you
1. check your task definition and see whether resource in your task looking good?
2. check your master and worker and see whether they exists and working fun?
3. check your master or worker log to see whether have detail error log?

**Comment by zhongjiajie** [comment]
duplicate #101

**Comment by Andy-xu-007** [comment]
YES, I have the same problem while using the pydolphinscheduler CLI to create workflow with YAML file, pydolphinscheduler's version im using is 4.0.3, and the version of dolphinscheduler is 3.1.7, a part of whole code as following:
`
  - name: child2
    task_type: Shell
    command: sh test1.sh
    fail_retry_times: 2
    fail_retry_interval: 3
    worker_group: worker252
    environment_name: worker-[252]-environment
    resource_list: [test1.sh]
    deps:
      - parent
`
 I'm used these code to generate workflow and the programe raise an error like below:
`
Auth token is default token, highly recommend add a token in production, especially you deploy in public network.
/home/hadoop/.local/lib/python3.8/site-packages/pydolphinscheduler/java_gateway.py:324: UserWarning: Using unmatched version of pydolphinscheduler (version 4.0.3) and Java gateway (version 3.1.7) may cause errors. We strongly recommend you to find the matched version (check: https://pypi.org/project/apache-dolphinscheduler)
  gateway = GatewayEntryPoint()
Traceback (most recent call last):
  File "/home/hadoop/.local/bin/pydolphinscheduler", line 8, in <module>
    sys.exit(cli())
  File "/home/hadoop/.local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/hadoop/.local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/hadoop/.local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hadoop/.local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hadoop/.local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/hadoop/.local/lib/python3.8/site-packages/pydolphinscheduler/cli/commands.py", line 106, in yaml
    create_workflow(yaml_file)
  File "/home/hadoop/.local/lib/python3.8/site-packages/pydolphinscheduler/core/yaml_workflow.py", line 494, in create_workflow
    YamlWorkflow.parse(yaml_file)
  File "/home/hadoop/.local/lib/python3.8/site-packages/pydolphinscheduler/core/yaml_workflow.py", line 235, in parse
    workflow_name = cls(yaml_file).create_workflow()
  File "/home/hadoop/.local/lib/python3.8/site-packages/pydolphinscheduler/core/yaml_workflow.py", line 179, in create_workflow
    task = self.parse_task(task_data, name2task)
  File "/home/hadoop/.local/lib/python3.8/site-packages/pydolphinscheduler/core/yaml_workflow.py", line 290, in parse_task
    task = task_cls(**task_params)
  File "/home/hadoop/.local/lib/python3.8/site-packages/pydolphinscheduler/tasks/shell.py", line 58, in __init__
    super().__init__(name, TaskType.SHELL, *args, **kwargs)
  File "/home/hadoop/.local/lib/python3.8/site-packages/pydolphinscheduler/core/task.py", line 222, in __init__
    self.get_content()
  File "/home/hadoop/.local/lib/python3.8/site-packages/pydolphinscheduler/core/task.py", line 332, in get_content
    res = self.get_plugin()
  File "/home/hadoop/.local/lib/python3.8/site-packages/pydolphinscheduler/core/task.py", line 319, in get_plugin
    raise PyResPluginException(
pydolphinscheduler.exceptions.PyResPluginException: The execution command of this task is a file, but the resource plugin is empty
`
the error remaind me to add resource plugin in YMAL file, resource center build on HDFS, after checking the source code and official doc, pydolphinscheduler support Local, GitHub, GitLab, OSS, S3, but not contain HDFS, so i should create a new resource plugin with HDFS? or do you have some other way can help me to create a workflow which can using resource center file with YAML file

[Looking forward to your reply](javascript:;)

**Comment by Treasure-u** [comment]
maybe you can try my fixed dolphinscheduler-sdk `https://github.com/Treasure-u/dolphinscheduler-sdk-python`

**Comment by zhongjiajie** [comment]
hi @Treasure-u @baratamavinash225 @Andy-xu-007 this issue already fix in https://github.com/apache/dolphinscheduler-sdk-python/pull/116 and we will release in version 4.0.4 within 3 days, thanks for your bug reports
